name       : unshield
version    : 1.5.1
release    : 7
source     :
    - https://github.com/twogood/unshield/archive/refs/tags/1.5.1.tar.gz : 34cd97ff1e6f764436d71676e3d6842dc7bd8e2dd5014068da5c560fe4661f60
license    : MIT
component  : programming.library
summary    : Library for manipulating InstallShield files
description: |
    Library for manipulating InstallShield files
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
