name       : unshield
version    : 1.4.3
release    : 6
source     :
    - https://github.com/twogood/unshield/archive/1.4.3.tar.gz : aa8c978dc0eb1158d266eaddcd1852d6d71620ddfc82807fe4bf2e19022b7bab
license    : MIT
component  : programming.library
summary    : Library for manipulating InstallShield files
description: |
    Library for manipulating InstallShield files
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
