name       : unshield
version    : 1.3
release    : 1
source     :
    - https://github.com/twogood/unshield/archive/1.3.tar.gz : 31a49c43b60e86b3ed731e0a1b988b88d35b755c85d103e93e1507278328bf73
license    : MIT
component  : programming
summary    : Library for manipulating InstallShield files
description: |
    Library for manipulating InstallShield files
builddeps  :
    - gcc
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
