name       : unshield
version    : 1.4.2
release    : 2
source     :
    - https://github.com/twogood/unshield/archive/1.4.2.tar.gz : 5dd4ea0c7e97ad8e3677ff3a254b116df08a5d041c2df8859aad5c4f88d1f774
license    : MIT
component  : programming
summary    : Library for manipulating InstallShield files
description: |
    Library for manipulating InstallShield files
setup      : |
    %cmake -DCMAKE_INSTALL_PREFIX=/usr \
           -DCMAKE_INSTALL_LIBDIR=%libdir% \
           .
build      : |
    %make
install    : |
    %make_install
